name: CI

on: push

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4


    - name: Display OS information
      run: |
        echo "Operating System: ${{ matrix.os }}"
        echo "Runner OS: ${{ runner.os }}"
        echo "Runner Architecture: ${{ runner.arch }}"

    - name: Test jq installation
      run: jq --version
